name: Build and Use Artifacts

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '12.x'

      - name: Build code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Release --property:PublishDir="${{env.DOTNET_ROOT}}\myapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          # Artifact name
          name: .net-app
          path: ${{env.DOTNET_ROOT}}\myapp

  deploy_job:
    runs-on: windows-latest
      
    steps:
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: .net-app
     
      - name: List files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
